
cget_validate_gh_src(repo/repo)
cget_validate_gh_src(repo)
cget_validate_gh_src(repo_21/repo@repo)
cget_validate_gh_src(repo_21repo@repo)
cget_validate_gh_src(repo.21repo.1@repo)
cget_validate_gh_src(repo-a12/name@master)
cget_validate_gh_src(Repo-a12/name@master)
cget_validate_gh_src(Repo-a12name@master)
cget_validate_gh_src(Repo-a12/name@1.0.0)
